### ISSUE TITLE
Drop support for Java < 8 and execute the requests using the non-blocking HTTP client

### ISSUE THREAD

**Issue by guizmaii** [auth0/auth0-java#144]
Hi,

Could be great to drop the support for Java versions inferiors to 8.
They're not maintained anymore and Java 8 brings great things for asynchronism.

Your clients still using older version of Java could still use previous versions of this lib.

A PR is already ready for the "execute the requests asynchronously" part of this issue here: https://github.com/auth0/auth0-java/pull/112

I make this issue to track the moves toward this goal.

Thanks,
Jules

**Comment by lbalmaceda** [comment]
Hey Jules, I agree. We'd like to release a new major eventually, removing deprecated endpoints and dropping support for Java7, but the priorities are different in our backlog today. I'll leave the issue open this time.
Cheers

**Comment by adrian-baker** [comment]
Isn't it better to leave it up to the caller to make the calls aynschronously?

**Comment by guizmaii** [comment]
@adrian-baker The thing here isn't about synchronicity nor asynchronicity but about thread blocking. Of course you can do thread blocking async calls but you'll have to manage that (ie. execute that call on an unbounded execution context. For more information, read this: https://gist.github.com/djspiewak/46b543800958cf61af6efa8e072bfd5c)

The HTTP client used in this lib provides an non-blocking async way to execute its calls. So, it's sad that this lib still does not provide the access to this functionality.

It's 2019, JDK11 is here. And we're still block by JDK7.

**Comment by lbalmaceda** [comment]
@guizmaii I don't see that major I mentioned coming anytime soon. What about exposing that async call as a method on the `Request` class? we would call enqueue internally in the implementation and you would need to pass a callback.

**Comment by guizmaii** [comment]
This is activity

**Comment by guizmaii** [comment]
This is activity

**Comment by guizmaii** [comment]
This is activity

**Comment by lbalmaceda** [comment]
@guizmaii Apologies for not being clear initially. We're still not planning the next major of this SDK. We should definitely target JDK 8 and consider offering both sync and async alternatives for invoking the requests in the next version, suitable for both Desktop and Backend clients. But given that today this is not in our roadmap, I cannot share an estimated date with you. 

What we could accept for this version is a PR that enables requests to be called asynchronously without introducing these breaking changes. Because internally we delegate the call to OkHttp, a solution to this problem could be implementing that "start" method [here](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/net/BaseRequest.java) and defining a callback class the user would specify.

Note, however, that because the `Request` interface is being returned in many methods of our API clients we cannot add the "start" method there. The usage will be limited to casting that received `Request` first to the right implementation class that has that method.

```java
Request<UserInfo> r = authApi.userInfo("accesstoken");
AsyncRequest<UserInfo> ar = (AsyncRequest) r;

ar.start(new Callback<UserInfo>() {
   public void onSuccess(UserInfo userinfo){
     //...
   }
   
   public void onFailure(Exception e){
     //...
   }
})
```

If that's something that works for your use case, feel free to open a PR and someone on my team will review it.

**Comment by guizmaii** [comment]
This is activity

**Comment by lbalmaceda** [comment]
@guizmaii as per my previous message, this is not in our backlog. If you need this change, I left some guidance above on a PR that we would accept to review and merge. I'll leave this open for a few more days in case you have any more questions.

**Comment by jimmyjames** [comment]
I think we should split this issue out into two valid (but obviously related) issues:
- Drop support for Java < 8
- Support async requests

I know that's a bit pedantic, but it will allow us to better capture the need to drop support for Java < 8 for many reasons, and the (reasonable) feature request for non-blocking HTTP requests.

While we set our build target for Java 7, the reality is that Java 8 is already required to use this SDK, brought in through third-party dependency updates. As mentioned in this thread, Java 7 is very dated, and we haven't received issues regarding not being able to run in Java 7. 

Also, there is precedence for updating to Java 8 minimum in a minor release, given the age of Java 7 and its lack of support. I don't think we need a new major to drop support for Java < 8, especially given that it already won't work with Java 7.

I'm assigning this issue to myself to prevent stale bot from trying to close it (should have done that earlier, apologies for the need to ping this issue, and thanks for doing that :)). I'll wait a couple days before splitting this issue, if there's any concerns please let us know.

**Comment by jimmyjames** [comment]
Split this into two issues: #314 and #315. Closing this issue, any additional conversation can be carried on in either of those issues. Thanks!
