### ISSUE TITLE
Access App metadata in IdToken

### ISSUE THREAD

**Issue by nartz** [auth0/auth0-java#173]
Hi - my goal is to be able to access the app metadata when a user authenticates themselves. I've properly added a Rule to copy the app metadata to the idToken, copying this:
https://community.auth0.com/t/how-to-retrieve-user-metadata-in-the-id-token/6667

Also i've added console.log does show the data in there properly.

How can I then access that app_metadata using auth0-java? The idToken is simply returned as a string, is there a way to decode it? Or do I need to make another request somehow?

```
        AuthRequest request = auth.login(username, password)
                .setAudience("myapp")
                .setScope("openid app_metadata");

            TokenHolder holder = request.execute();
            String token = holder.getIdToken();

```

Thanks!

**Comment by nartz** [comment]
Ah it appears it is showing up when calling userInfo now - although not sure what changed while I was debugging (maybe just slow to propogate the rules on the auth0 side...)

**Comment by lbalmaceda** [comment]
If you're going to use the contents of the `id_token` you should first verify it's signature (otherwise you shouldn't trust it). You can do that with any JWT library that accepts RS256 algorithm verification by pulling its cert from your domain's `.well-known` path. Alternatively, you can make a second request to the /userinfo endpoint like you did above using the received `access_token`, and the information in there should match the payload of the `id_token`. The contents will depend in the **scope** that you requested on authentication, plus anything that you're doing in the rule.
