### ISSUE TITLE
Created user does not return a user id

### ISSUE THREAD

**Issue by pbodor** [auth0/auth0-java#176]
CreatedUser returned by AuthAPI#signUp does not return userId correctly. Json mapping is using "_id" while the response json is "user_id".

**Comment by lbalmaceda** [comment]
Thanks for the report! I guess this was taken from the docs https://auth0.com/docs/api/authentication#signup. I'll also notify the team responsible for that page so we can all be on sync.

![image](https://user-images.githubusercontent.com/3900123/48784002-84c24400-ecc0-11e8-92f5-ce22647cff7e.png)

**Comment by lbalmaceda** [comment]
@pbodor I just tried this via curl and the id comes as the image attached above in the `_id` property. How are you calling this endpoint?

**Comment by pbodor** [comment]
This is using the java sdk AuthAPI.signUp(...) method. In debugger I can see the following:
![image](https://user-images.githubusercontent.com/29469591/48803389-a4b43f00-ed76-11e8-91fa-a59644bcd3e4.png)

you can see that "user_id" in response body does not match the CreatedUser expected "_id".

**Comment by pbodor** [comment]
We're using a custom DB. We have a number of rules in place, but I still get the issue when all of them are disabled.

**Comment by lbalmaceda** [comment]
@pbodor This seems to happen only for custom db connections at this time. Alternatively you could log the user in and call the [/userinfo endpoint](https://auth0.com/docs/api/authentication#user-profile) using the access token or find the `sub` claim inside the ID token payload.

I've commented this internally since it's not an error of this SDK but I suggest you raise a ticket through https://support.auth0.com if possible so this is given a higher priority.

**Comment by damieng** [comment]
Related https://github.com/auth0/auth0.net/issues/304

**Comment by damieng** [comment]
The rule is that `_id` is returned when using a standard connection and `user_id` when using a custom connection.  We should add both properties to the deserialized response class with appropriate comments.

**Comment by damieng** [comment]
@lbalmaceda Here's how I'm solving it in Auth0.Net https://github.com/auth0/auth0.net/pull/351/commits/91d601c540cfb956f7c4c265ea8ec848e97277a8 after confirming the options with IAM.
