### ISSUE TITLE
tokenHolder.getExpiresIn documentation doesn't match behavior

### ISSUE THREAD

**Issue by danebert** [auth0/auth0-java#211]
tokenHolder.getExpiresIn appears to return seconds-till-expiry (as the method name implies) ... but the JavaDoc says it returns a time "Getter for the expiration time ('exp' claim) of the recently issued token." ... which would be a time in epoch seconds.

https://github.com/auth0/auth0-java/blob/7ab4d2d65d9e9882eed755f770f921bc21c8adce/src/main/java/com/auth0/json/auth/TokenHolder.java#L67

Suggested documenation update:

```
    /**
     * Getter for the expiration duration in seconds of the recently issued token.
     *
     * @return seconds until the token expires or null if missing.
     */
```

**Comment by lbalmaceda** [comment]
`expires_in` is the property that the server returns when you authenticate, and it tells you in how many seconds (since the tokens were issued) the access token would be deemed invalid. It is not calculated dynamically, so unless you keep the time at which you have requested the token, this property would not have much value for you.

I think your suggestion is too similar to what we have today. What about remarking that this is "since it was issued"?


> Getter for the amount of seconds that need to be elapsed since the tokens were issued by the authorization server, in which the access token will be deemed invalid.

**Comment by danebert** [comment]
The part of the JavaDoc that was confusing was this: "Getter for the expiration time ('exp' claim) of the recently issued token."

That could be interpreted as the time of expiration (in epoch seconds) ... which is what happened ... and caused a bug.

How about:
```
Getter for the expiration duration, in seconds, since the token was issued.
@returns number of seconds, from token issue time, until the token expires
```

**Comment by lbalmaceda** [comment]
I see your point now.

- `exp` is the "date time" at which the token should no longer be accepted. But that is contained inside the token's payload.
- `expires_in` is a property sent by the authentication server, that represents the "duration" of the token (vs the "expiration" date above) since it was issued. 

So `Time.now()` + `expires_in` should match `exp`, time duration speaking.



I think the javadoc should say:
```
Getter for the duration of this token in seconds since it was issued.
@returns the number of seconds in which this token will expire, since the time it was issued.
```

(I'd remove the "expiration duration" to lower the confusion). What do you think?

**Comment by danebert** [comment]
I like your suggestion. Thanks for listening to the feedback!
