### ISSUE TITLE
Feature Request: Handle Token Refresh for Management API Client

### ISSUE THREAD

**Issue by notori0us** [auth0/auth0-java#212]
In the [node-auth0 Management API SDK](https://github.com/auth0/node-auth0#management-api-client), a developer can provide a token or a clientId/clientSecret.

When providing a clientId/clientSecret combination the developer is then not required to implement token refresh logic, which is immensely helpful.

Is there any plan to offer similar functionality to the Java SDK? Thank you.

**Comment by lbalmaceda** [comment]
There's nothing planned similar to that. There's a method though to [update the token](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/mgmt/ManagementAPI.java#L57) that was originally set. But nothing is done automatically. I suggest you make the feature request in the [feedback form](https://auth0.com/feedback) since that reaches directly our Product team and they can evaluate and prioritize it.

**Comment by krisnik** [comment]
Understand this is an old thread, but couldn't find any material for this topic. So, @joshcanhelp @lbalmaceda - Is there a recommended way of handling Management API token refresh? 

In my mind there are three ways.. 
1. Handle the API exception, refresh token and re-run the request. 
2. Store `tokenExpiresAt` and refresh the token when `managementAPI` instance is required. Something in the lines of 
```java
public ManagementAPI getManagementAPI() {

    if (currentTime > tokenExpiresAt) {
        refreshToken();
        managementApi.setApiToken("new token");
    }

    return managementApi;
}
```
3. Have a background thread that refreshes the token at defined periodicity. 

All three options have some level of drawbacks. 

For 1, retries should be handled at each Auth0 call. the code becomes repetitive. 
In 2, we cannot let callers cache managementAPI object. They should always use `getManagementAPI()`. 
In case of 3, additional handling is required to ensure that the background thread is re-created if it crashes for any reason. 

Please share your suggestions and thoughts.
