### ISSUE TITLE
MgmtApi does not allow deleting fields for user

### ISSUE THREAD

**Issue by peadardefaoite** [auth0/auth0-java#239]
### Description

If I do a PATCH request to `/api/v2/users/{id}` with a field set to `null` with curl, it erases that field. If I try using the Java Auth0 SDK, it has no effect.

The SDK does not allow deletion of fields within a user's metadata as the User class ignores null fields when marshalling to JSON. Null fields are used in the PATCH request to erase fields and their values. 

[Docs](https://auth0.com/docs/users/guides/update-metadata-properties-with-management-api) about PATCH'ing with `null` values.
[User class](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/mgmt/users/User.java
) with the Jackson annotation that ignores null values.

### Reproduction

```java
ManagementAPI managementAPI = new ManagementAPI(clientDomain, apiToken);
User user = users().get(userId, null); // user with given name set
Request<User> requestGet = managementAPI.users().get(userId, null);
try {
     user = requestGet.execute();
} catch (Auth0Exception ex) {
     throw ex;
}

user.setGivenName(null);
Request<User> requestPatch = managementAPI.users().update(userId, user);
try {
     user = requestPatch.execute(); // overwrite user
} catch (Auth0Exception ex) {
     throw ex;
}

System.out.println("User Given Name: " + user.getGivenName()); // is not null
```

### Environment

- **Version of this library used:** 1.15.0
- **Version of the platform or framework used, if applicable:** Spring Boot 2.2
- **Other relevant versions (language, server software, OS, browser):** None
- **Other modules/plugins/libraries that might be involved:** Spring, Jackson

**Comment by lbalmaceda** [comment]
👋 Thanks for the report! We've reviewed this and agree it's an issue. We're tracking this internally and will come up with a solution soon.

**Comment by jimmyjames** [comment]
Hi @peadardefaoite, you are correct that we do not marshal null values on the `User` class (or other models) when sending requests. Allowing null fields to be sent on the `User` class would have unintended side effects, however, as we use that class for other request types involving users.

At some point, it may make sense to introduce request/response specific classes, which would make it easier to allow nulls to be sent where needed (along with more closely modeling the actual request/response objects). Even then we'd need to be careful since it might be easy to unintentionally erase fields by sending nulls for unset properties on the domain object.

For now, your best path forward for this specific use case will be to either send the request manually, or extend the `User` class and specify `@JsonInclude(JsonInclude.Include.ALWAYS)` for fields that you would like to send null values (just being careful about unintentionally erasing fields as discussed above).
