### ISSUE TITLE
AuthAPI client secret should be optional [SDK-2001]

### ISSUE THREAD

**Issue by mr-newell** [auth0/auth0-java#273]
The client secret is not required in certain cases (for example, [refreshing a token](https://auth0.com/docs/tokens/guides/use-refresh-tokens) in a non-confidential application) however it is [not possible](https://github.com/auth0/auth0-java/blob/b80f561657f994112deb1a04f26d3252db694d6c/src/main/java/com/auth0/client/auth/AuthAPI.java#L64) to create an `AuthAPI` instance without one.

**Comment by lbalmaceda** [comment]
Yes, that makes sense. I imagine the most straightforward fix is to make it optional (e.g. remove the assert non-null call) and add the corresponding unit tests and docs; without introducing new constructor variants.
Would you send a PR to fix that?

**Comment by mr-newell** [comment]
Most tests assert that the secret is present; should these checks be removed or left alone? From my understanding the use of the client secret is dependent on whether the application is confidential or public but I don't know if there are certain endpoints which will always require the secret (Management API calls, for instance, will always be from a secure backend).

**Comment by lbalmaceda** [comment]
The `ManagementAPI` class should remain unchanged since it uses an access token with the proper scopes to consume its endpoints. What will change is the `AuthAPI` class.

Make the `clientSecret` param in both constructors optional by removing the `assertNotNull` call. Document that on the param Javadoc. Something around 
> "Required when the 'Token Endpoint Authentication Method' field at your Application Settings is Post or Basic. Read more about confidential apps at https://auth0.com/docs/applications/concepts/app-types-confidential-public#confidential-applications".

Similarly, update the docs on the following methods where the client_secret is optional depending on those cases above; adding a paragraph before the params are listed, explaining that the class should be initialized with a valid `client_secret` in those cases. The methods where this is optional are:

```java
public AuthRequest login(String emailOrUsername, char[] password)

public AuthRequest login(String emailOrUsername, char[] password, String realm)

public Request<Void> revokeToken(String refreshToken)

public AuthRequest renewAuth(String refreshToken)
```

There are also a few methods where this is required. Here I'll ask you to both document it as required and add the `assertNotNull` call so we fail when called without it first being set.

```java
public AuthRequest requestToken(String audience) 

public AuthRequest exchangeCode(String code, String redirectUri)
```

> Note since this SDK doesn't support PKCE for now, we will make the secret required on that `exchangeCode` call above. If we need to support PKCE we would probably do so on a separate method that has a more descriptive name (e.g. "exchangeCodePKCE") and also accepts the verifier value.

Finally, remember to update or add the required unit tests to assert the introduced changes.

**Comment by lbalmaceda** [comment]
Tracking internally `SDK-2001`

**Comment by abazlinton** [comment]
it would be good if this could be fixed. For those seeking a workaround - I managed to get `userInfo` to work with an empty string supplied as the `clientSecret` e.g.

 `new AuthAPI(<domain>, <clientId>, "");`
