### ISSUE TITLE
Custom Exception for MFA challenge on login [SDK-1998]

### ISSUE THREAD

**Issue by ali-nutmeg** [auth0/auth0-java#279]
By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> The login request in AuthRequest.execute returns a `TokenHolder` on successful login request. If MFA is required, it throws a generic `APIException` and I need to manually get the values for the MFA results from a String Map

### Describe the ideal solution

> A custom exception that has the MFA token as a well defined variable

## Alternatives and current work-arounds

> What I do right now is exception.getValue("mfa_token").toString() which is quite clunky.

### Additional context

> n/a

**Comment by lbalmaceda** [comment]
👍  Can you post the response error body you receive? Thanks

**Comment by ali-nutmeg** [comment]
Hi.

The MFA response body looks like:
```
{
    "error": "mfa_required",
    "error_description": "Multifactor authentication required",
    "mfa_token": "Fe26.2*a60a93*JR..."
}
```

This is expected as per documentation.

When making a call to `AuthRequest.execute`, it then maps to `com.auth0.exception.ApiException`

You can see this happening here - https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/net/ExtendedBaseRequest.java#L131

What I would like is another if condition added here (https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/net/ExtendedBaseRequest.java#L122) to check for 403 MFA required and throw a custom MfaRequiredException

**Comment by ali-nutmeg** [comment]
To add to above, there also does not seem to be a way to submit an otp from MFA using this library.

I'm specifically after something in the library that can action "Verify with one time password" as documented here - https://auth0.com/docs/api/authentication#verify-with-one-time-password-otp-

**Comment by lbalmaceda** [comment]
I'm not sure if the "MFA required" error should be considered as a separate exception. One thing is being rate limited by the server, but this one is just another "API error" due to the server not liking one value sent in the authentication request. Accepting this change could set precedence and anyone could come and ask for their custom exception class/subclass on a particular API error code.

I know that in other SDKs [we have some basic matcher](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.java#L156-L239) logic to expose different errors. Maybe that's something we can add to the `APIException` class. Do you think that can help your use case @ali-nutmeg ?

**Comment by ali-nutmeg** [comment]
I think whether it's adding logic to expose different errors using the android API you linked or having separate exception types both result in me getting the information I need, so I don't mind if it's done either way.

It would really be useful to have either implementation as it saves me (and every other java client) needing to implement this manually.

**Comment by lbalmaceda** [comment]
Sounds good! Tracking internally as `SDK-1998`
