### ISSUE TITLE
invalid_request: Missing required parameter: nonce

### ISSUE THREAD

**Issue by siauderman** [auth0/auth0-java#361]
Hi, I'm trying to use auth0-java in my desktop app. I generate a URL as such:
````
authAPI.authorizeUrl("https://localhost/").withResponseType("token id_token").withScope("openid profile email app_metadata user_metadata client_metadata").withAudience("https://customautosys.auth0.com/userinfo").build()
````
However, I get this error: invalid_request: Missing required parameter: nonce
How do I generate the nonce?
![bildo](https://user-images.githubusercontent.com/14951259/125497333-243394a7-6a21-4ace-89d7-fdb6a800c9f0.png)
If I use only token instead of token id_token it can load - however, I need the id_token.

**Comment by jimmyjames** [comment]
👋 hi @siauderman,

You can add any parameters to the authorization URL using `withParameter` when building the auth URL. Here is some [documentation](https://auth0.com/docs/authorization/mitigate-replay-attacks-when-using-the-implicit-flow) about what the nonce is and how to generate one.

However, it should be noted that this SDK does not explicitly support desktop clients for authentication, as the `AuthAPI` requires a client secret and doesn't provide any provide first-class support for the[ Authorization Code + PKCE flow](https://auth0.com/docs/flows/add-login-using-the-authorization-code-flow-with-pkce).

You could try generating a code verifier and challenge using the example in the documentation referenced above, and then using the `code` response type and `withParameter` method on the authorization URL builder to include the `code_challenge` and `code_challlenge_method` parameters on the authorization URL. And then the authorization code can be exchanged for tokens, passing the `code_verifier` parameter with the `addParameter` method when calling `exchangeCode`. Note this should be done using an Auth0 application of "Native" type, and since this is a desktop (public) client, instead of using a secret you could try passing an empty string to construct the `AuthAPI`. It's not ideal but it may work.

We may add some first-class PKCE support to the SDK in the future, but that's not on the immediate roadmap, so you may wish to try something like discussed above and in the referenced documentation. Hope that helps!

**Comment by siauderman** [comment]
I managed to get it working by just generating a random nonce using java.security.SecureRandom. Thanks!

Yes, I understand you don't support desktop Java apps - but how else would I use my existing auth0 user database with my apps (which among other things may be deployed to desktop)? I have no choice but to use JCEF to login with auth0.
