### ISSUE TITLE
Allow to instrument Http requests made by the okhttp client

### ISSUE THREAD

**Issue by Legion2** [auth0/auth0-java#409]
### Describe the problem you'd like to have solved

We want to use distributed tracing with opentelemetry and also want to trace requests made to auth0 using the sdk. Therefore we want to add the [opentelemetry OkHttp instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/okhttp/okhttp-3.0/library) to the internal OkHttp client of the auth0 sdk.

### Describe the ideal solution

There is an option to add or enable the instumentation to the internal OkHttp client manged by the sdk.

## Alternatives and current work-arounds

Use the auto instrumentation which requires a javaagent runtime, which is not an opion

### Additional information, if any

We use quarkus which produces a native executable without a full jvm, so we can not use the javaagent option for instrumentation.

**Comment by macalac** [comment]
👍 That would be great to have. We are about to integrate with auth0 and would love some http.client metrics being available out of the box. Looking forward to the next major release :)

**Comment by poovamraj** [comment]
Hello @Legion2 and @macalac, thanks for reaching out regarding this feature. We have noted this down internally and tracking it under ticket 3520. We are planning provide an update for this library in which we will be hopefully implementing this feature. We will let you know once this is done and until then we are closing this since there is already an internal tracker. Please feel to provide comments or feedbacks regarding this feature as well
