### ISSUE TITLE
OkHttpClient - A connection to [issuer] was leaked

### ISSUE THREAD

**Issue by shiloa** [auth0/auth0-java#42]
Hi,

We're using `com.auth0:auth0:1.0.0` and `com.auth0:auth0-spring-security-api:1.0.0-rc2` inside a spring-boot `1.5.1.RELEASE` application. When calling the Auth0 API, we occasionally see a log warning that apparently emanates from `okhttp3`:

```
2017-02-27T08:05:05.453 WARN  okhttp3.OkHttpClient - A connection to https://[our-issuer-id].auth0.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

Looking it up it seems the possible cause is that the body of the request needs to be explicitly closed when the response code is not 200.  See https://github.com/square/okhttp/issues/2311.

Thanks!

**Comment by lbalmaceda** [comment]
Hi @shiloa,
We fixed that in https://github.com/auth0/auth0-java/pull/38. You'll see it in the next release.

Cheers,

**Comment by shiloa** [comment]
thanks @lbalmaceda.

**Comment by AlphaJuliettOmega** [comment]
@lbalmaceda how do I know if there was a regression on this issue or if it's a new issue?

I don't know how to reproduce or get more info but I'm seeing this in my logging:
```
W/okhttp.OkHttpClient: A connection to http://10.0.2.2:8081/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

And I can't find much about this anywhere else (I'm using React-native-intercom 18, upgrade to 19 didn't change it)

**Comment by lbalmaceda** [comment]
I'm not sure. Since then, we wrapped the access to the response body both when parsing a 2xx ([here](https://github.com/auth0/auth0-java/blob/61865c77bd9cc2eaa63afb01c2d7df06cee86713/src/main/java/com/auth0/net/ExtendedBaseRequest.java#L69)) or an error response ([here](https://github.com/auth0/auth0-java/blob/61865c77bd9cc2eaa63afb01c2d7df06cee86713/src/main/java/com/auth0/net/ExtendedBaseRequest.java#L127)). With what version of the `Auth0-Java` SDK are you seeing this?

**Comment by benwaffle** [comment]
I am also seeing this in 1.29.0
