### ISSUE TITLE
Provide tokeninfo method

### ISSUE THREAD

**Issue by amertum** [auth0/auth0-java#43]
I've just migrate from `0.4` to `1.0` and I'm missing the `AuthenticationAPIClient#tokenInfo(idToken)` method.

I'm using lock with JWT for my single page application. I call my API passing the JWT as Authentication header. I then use the JWT to retrieve the user info by calling `#tokenInfo`.

With the new `1.0` version, I have not find the `#tokenInfo` method which is documented here https://auth0.com/docs/api/authentication?http#get-token-info
I've only found `AuthAPI#userInfo` but it requires an `access_token`.

Is it possible to add such `#tokenInfo` method in `AuthAPI` ? Or is there a new way to handle that situation ?

**Comment by hzalaz** [comment]
@amertum ideally you could decode the token (after verifying it) and get some user info from its claims. If you need the full user profile I'd recommend calling Management API https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id

To get a token to call it you can use [client-credentials](https://auth0.com/docs/api-auth/config/asking-for-access-tokens) to get a token for your backend (there is no need to get one per user).

We are not going to add `/tokeninfo` since we recommend using api2 to get the user's profile
