### ISSUE TITLE
Update of name, familyName, givenName fails with API v2, and should be @deprecated

### ISSUE THREAD

**Issue by nealeu** [auth0/auth0-java#60]
The User class contains these, but they are not supported, with the API returning a message suggesting to use user_metadata instead.

They should be at least deprecated in the Javadoc so that developers know that they should migrate away from using them.

**Comment by lbalmaceda** [comment]
@nealeu those setters work when you're trying to **create a new user**. There are, of course, values that don't make sense to change once you've set them, like the `name`. If you do need to change them you'll have to delete the user and create it again.

**Comment by nealeu** [comment]
Sorry, but  can you be a bit clearer here.  The Javadoc on those properties is "content free" (i.e. it states what is already obvious).  

I'm suggesting that some greater clarity could be provided and you've just closed the issue.

Also, what are we supposed to do when we, as happens, someone gets married, or has a gender re-assignment?  Given name and family name can change.

We should not have to delete the user for this scenario.

**Comment by nealeu** [comment]
By the way.  Having removed updates to the names, I am getting issues with it telling me that I cannot make updates to the password and emailVerified at the same time when I'm not attempting to change either of them.

**Comment by hzalaz** [comment]
@nealeu some root attributes are not allowed to be modified not by design of this SDK but of the [API](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id). The POJO of User it has a dual use for POST and PATCH and that's why it has all those setters since when you create the user you can define those values. However we will explore an alternative like having a different POJO for PATCH since the rules are different (Opened a new issue #61).

**Comment by nealeu** [comment]
Thanks. That would make sense.
