### ISSUE TITLE
When updating user it's not possible to unset optional fields

### ISSUE THREAD

**Issue by Milena92** [auth0/auth0-java#622]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-java#readme) and [Examples](https://github.com/auth0/auth0-java/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-java/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When attempting to update a user to remove the nickname or name fields using the Auth0 Java SDK, passing null values does not unset these fields as expected. This behavior is inconsistent with the results when making direct API requests, where passing null successfully unsets these fields. Passing an empty string is not a viable workaround due to API validation constraints that prevent empty strings from being accepted for these fields.

### Reproduction

1. Use the Auth0 Java Client to fetch a user.
2. Attempt to update the user, setting the nickname or first name field to null to indicate it should be unset.
3. Observe the result of the update operation and fetch the user again to verify if the field was unset.

### Additional context

Passing null for the nickname or first name fields using the Auth0 Java Client does not unset these fields. The fields remain unchanged in the user's profile, indicating the null value is either not being serialized or not processed by the Auth0 Java Client in the same manner as direct API requests.

### auth0-java version

2.1.0

### Java version

21

**Comment by jimmyjames** [comment]
Thanks for the report @Milena92! Yes, this is an issue in this and other typed SDKs unfortunately. The problem is that in certain cases (like you described, to unset a field) we want to send null, but in the majority of cases we should never send null values, as it could inadvertently unset values. For example, if you want to just update a single field on an entity, if we send null values that means every field would have to be set to its current/desired value or it would be unset. I think if it's even possible to address this issue, we'd at a minimum need to start with splitting out request/response objects, instead of using a single domain for both request and response as we do today. But even then I'm not sure how we'd either selectively send nulls or ensure good DX when just trying to update a single field, for example.

**Comment by tanya732** [comment]
Hi @Milena92 

As @jimmyjames added we should never send null values, as it could inadvertently unset values.

But yeah, there are few ways to make this work : 

1. You can create a custom wrapper class that extends the existing User class. This wrapper class will ensure that certain fields (like nickname) are always included in the JSON representation, even if their values are null.

Sample code snippet

`
public class CustomUser extends User{
    @JsonInclude(JsonInclude.Include.ALWAYS)
    @JsonProperty("nickname")
    private String nickName;
}`

2. Use the custom wrapper class when updating the user to ensure that null values are properly handled.

Sample code snippet

`
 CustomUser customUser = new CustomUser();
 customUser.setNickname(null);
 managementAPI.users().update(userId, **customUser**).execute();
 `
 
 Please let me know your thoughts about this work around.
 
 Thank you!!

**Comment by Milena92** [comment]
Hi @tanya732 regarding this "As @jimmyjames added we should never send null values, as it could inadvertently unset values." that's exactly my point, I do want to unset it completely. I can do that via Management API, why not via SDK? I'm also experiencing another issue: 
I'm trying to use Private Key JWT authentication method and when since client_authentication_methods and token_endpoint_auth_method are mutually exclusive, they can't both have value, so one of them has to be null.

So something like this in case I want to use again "client_secret_post" method. Which currently isn't possible with the SDK as I'm aware due to this issue.

```
curl --location --request PATCH 'https://{domain}/api/v2/clients/{clientId} \
  --header 'Authorization: Bearer {managementApiAccessToken} \
  --header 'Content-Type: application/json' \
  --data-raw '{
          "token_endpoint_auth_method": "{tokenEndpointAuthMethod}", 
          "client_authentication_methods": null
   }​​'​​
```

**Comment by tanya732** [comment]
Hi @Milena92

I just wanted to follow up on this issue. Have you had a chance to try the workaround. If it resolved the problem, please let me know, and we can consider this issue closed.

**Comment by Milena92** [comment]
HI @tanya732 yes, workaround worked. Thank you so much!

**Comment by prestongilchrist** [comment]
Would it be possible to support objects that use the Java 8 Optional or JsonNullable container so that it can adequately represent the following states:

1. A property that has not been set (empty).
2. A property that has been set to null.
3. A property that has been set to a value.

And can be effectively serialized with explicitly set nulls and values in the JSON,  but unset values omitted from the JSON?
