### ISSUE TITLE
Managing Signup and Login using Oauth 2 Accesstoken

### ISSUE THREAD

**Issue by Vo0Do0** [auth0/auth0-java#70]
Hi @lbalmaceda 

First of all thanks for this SDK. Now I can manage regular login and signup with the help of this plugin. But I couldn't able find suitable apis which handle the social Signup and login using Oauth 2 Token. I have a custom login page in my front end which gives Oauth 2 token on successful login in social media like google and facebook. So I want to use this tokens for signing up and login of my users. Can you please guide me to implement this?

Thanks in advance.

**Comment by jspetrak** [comment]
Hello @Vo0Do0 usually you use social websites as identity providers. This means, you would need to use Auth0 login page in order to enable the social login. You can read more about Facebook [here](https://auth0.com/docs/connections/social/facebook). Other social logins are also documented.

**Comment by lbalmaceda** [comment]
@Vo0Do0 The [endpoint](https://auth0.com/docs/api/authentication#social-with-provider-s-access-token) you mention was removed and it's no longer enabled for new clients as it's not OIDC conformant. We might get it back in the future if we accomplish that but we can't provide any date now.

As of today, the easiest way to do social signup/login is using the Auth0 _Hosted Login Page_. In your client enable the social providers you require (like @jspetrak said you can use your own "app id" and stuff like that or stick to the auth0 defaults) and then just redirect the user to the `/authorize` endpoint. That will show the Lock web widget (or whatever you've configured in the hosted pages settings of the dashboard) with all the enabled providers. You can also call that URL passing a specific connection name, so it directly uses that one instead of prompting the user to choose one. After the user signs in on the provider's site, he'll be redirected back to the widget which will process the authentication and return an auth0 access_token for you to use. Check the readme [here](https://github.com/auth0/auth0-java#authorize---authorize) to learn how to customize the authorize URL. And don't hesitate to ask questions [here](https://support.auth0.com) or [here](https://community.auth0.com)
