### ISSUE TITLE
Feature Request: Allow sending client ip as `auth0-forwarded-for` header for password grant

### ISSUE THREAD

**Issue by ashishdasnurkar** [auth0/auth0-java#72]
As required in this https://auth0.com/docs/api-auth/tutorials/using-resource-owner-password-from-server-side#brute-force-protection-and-server-side-apis

**Comment by lbalmaceda** [comment]
@ashishdasnurkar I'd rather make the `Request` class support setting custom headers and let the user do that manually, as not all the endpoints support this. I'll leave the issues open as a reminder.

**Comment by rcumberlandnm** [comment]
@lbalmaceda Apologies for resurrecting an old issue, but we've also hit the scenario where we'd like to set the `auth0-forwarded-for` header in our requests to Auth0. At the moment we're forced to cast to `TokenRequest` as that's what `AuthAPI` creates and returns internally, in order to set this header. Any chance of making the API publicly accessible?
https://github.com/auth0/auth0-java/blob/a265f3224cd64847774d71c15ea2718b2c80c1dc/src/main/java/com/auth0/net/CustomizableRequest.java#L19

**Comment by lbalmaceda** [comment]
@rcumberlandnm We keep the return type as `Request`. Casting the class has been the approach we have been recommending so far for extending the default behavior. There's no private API in that sense, once you cast it you get access to the public methods to add headers/params.

A non-breaking solution for this use case could be refactoring the signatures to return the type of request that is being created there. e.g. in this case, make it return a `TokenRequest` instead of a `Request`. That also means we lose some flexibility to extend this class internally. I'm not saying there's anything planned so far but it is good to understand the scope of a change.

**Comment by rcumberlandnm** [comment]
I think returning `TokenRequest` from `AuthAPI::login` would be a good solution, as the type is covariant with the existing return type `AuthRequest`:
https://github.com/auth0/auth0-java/blob/a265f3224cd64847774d71c15ea2718b2c80c1dc/src/main/java/com/auth0/client/auth/AuthAPI.java#L468
https://github.com/auth0/auth0-java/blob/a265f3224cd64847774d71c15ea2718b2c80c1dc/src/main/java/com/auth0/net/TokenRequest.java#L7

**Comment by lbalmaceda** [comment]
That's what I was talking about 🎉 , subclasses or implementations of Request can be safely returned without introducing breaking changes. But I'm not too convinced of going with that approach. I understand it's an easy solution and really fast to implement. 

My concern is we could leak exposure of methods we don't really intend devs to access in some scenarios. I've added a task in our backlog (SDK-1748 for our internal reference) for us to evaluate this feature request. The idea I have is to introduce yet another subclass or implementation of Request (again: not to break) but that only allows to add parameters and headers.

**Comment by rcumberlandnm** [comment]
I'm all for that approach, sounds good. Ultimately all I'd personally like to have is a way to use the `auth0-forwarded-for` header in a public API, rather than having to cast and set a header. If that means I need to set a header via a public API, that's good too!

Thanks for considering this by the way, it's appreciated.
